#ifndef DOPPELKOPF_WINDOWSETTINGS_HPP
#define DOPPELKOPF_WINDOWSETTINGS_HPP

#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 720

#define CARD_WIDTH WINDOW_WIDTH / 15
#define CARD_HEIGHT WINDOW_HEIGHT / 10

#define NUMBER_OF_CARDS 40
#define NUMBER_OF_PLAYERS 4
#define NUMBER_OF_CARDS_PER_PLAYER 10





#endif //DOPPELKOPF_WINDOWSETTINGS_HPP
